//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18n.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Alternatively, select a map file below: 的本地化字符串。
        /// </summary>
        public static string Alternatively__select_a_map_file_below_ {
            get {
                return ResourceManager.GetString("Alternatively, select a map file below:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        public static string Browse___ {
            get {
                return ResourceManager.GetString("Browse...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created by Rampastring 的本地化字符串。
        /// </summary>
        public static string Created_by_Rampastring {
            get {
                return ResourceManager.GetString("Created by Rampastring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create new map! Returned error message: 的本地化字符串。
        /// </summary>
        public static string Failed_to_create_new_map__Returned_error_message_ {
            get {
                return ResourceManager.GetString("Failed to create new map! Returned error message:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Map... 的本地化字符串。
        /// </summary>
        public static string New_Map___ {
            get {
                return ResourceManager.GetString("New Map...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path of the map file to load (can be relative to game directory): 的本地化字符串。
        /// </summary>
        public static string Path_of_the_map_file_to_load__can_be_relative_to_game_directory__ {
            get {
                return ResourceManager.GetString("Path of the map file to load (can be relative to game directory):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to the game directory: 的本地化字符串。
        /// </summary>
        public static string Path_to_the_game_directory_ {
            get {
                return ResourceManager.GetString("Path to the game directory:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent files: 的本地化字符串。
        /// </summary>
        public static string Recent_files_ {
            get {
                return ResourceManager.GetString("Recent files:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The map editor failed to launch.\r\n\r\nReason: {0} \r\n\r\n Stack trace: {1} 的本地化字符串。
        /// </summary>
        public static string The_map_editor_failed_to_launch {
            get {
                return ResourceManager.GetString("The map editor failed to launch", resourceCulture);
            }
        }
    }
}
